package init

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/StephanSchmidt/human/errors"
	"github.com/StephanSchmidt/human/internal/claude"
)

type projectConfigStep struct{}

// NewProjectConfigStep creates a WizardStep that ensures .humanconfig.yaml
// has a project: field and devcontainer: section for agent readiness.
func NewProjectConfigStep() WizardStep {
	return &projectConfigStep{}
}

func (s *projectConfigStep) Name() string { return "project-config" }

func (s *projectConfigStep) Run(w io.Writer, fw claude.FileWriter) ([]string, error) {
	existing, _ := fw.ReadFile(configPath)
	content := string(existing)

	var additions []string

	if !hasYAMLKey(content, "project") {
		cwd, err := os.Getwd()
		if err != nil {
			return nil, errors.WrapWithDetails(err, "determining project name")
		}
		additions = append(additions, fmt.Sprintf("project: %s", yamlSafeString(filepath.Base(cwd))))
	}

	if !hasYAMLKey(content, "devcontainer") {
		if _, err := fw.ReadFile(devcontainerPath); err == nil {
			additions = append(additions, "devcontainer:\n  configdir: \".\"")
		}
	}

	if len(additions) == 0 {
		return nil, nil
	}

	var buf strings.Builder
	if len(content) > 0 {
		buf.WriteString(strings.TrimRight(content, "\n"))
		buf.WriteString("\n\n")
	}
	buf.WriteString(strings.Join(additions, "\n\n"))
	buf.WriteString("\n")

	if err := fw.WriteFile(configPath, []byte(buf.String()), 0o644); err != nil {
		return nil, errors.WrapWithDetails(err, "writing project config", "path", configPath)
	}

	_, _ = fmt.Fprintf(w, "Updated %s with project settings\n", configPath)
	return nil, nil
}

// hasYAMLKey checks if a top-level YAML key exists in the content.
// Uses line-start matching since the config is generated by our own templates.
func hasYAMLKey(content, key string) bool {
	prefix := key + ":"
	for _, line := range strings.Split(content, "\n") {
		if strings.HasPrefix(line, prefix) {
			return true
		}
	}
	return false
}
